# version: '3'
# services:
#   mongo:
#     image: winkelzoeker/winkelzoeker-db
#     container_name: 'winkelzoeker-mongodb'
#     restart: always
#     ports:
#       - 27017:27017
#     volumes:
#       - ~/data:/data/db
#     expose:
#       - 27017
#   adminmongo:
#     image: mrvautin/adminmongo
#     ports:
#       - 1234:1234
#     environment:
#       - HOST=0.0.0.0
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: 'winkelzoeker-mongodb'
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=winkelzoeker-database
      - MONGO_INITDB_ROOT_USERNAME=winkelzoeker-root
      - MONGO_INITDB_ROOT_PASSWORD=winkelzoeker-passwd
    volumes:
      - ~/data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: winkelzoeker-root
      ME_CONFIG_MONGODB_ADMINPASSWORD: winkelzoeker-passwd